//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTA1
    {
        public ACTA1()
        {
            this.PRACTICA = new HashSet<PRACTICA>();
        }
    
        public short IDACTA1 { get; set; }
        public string OBSERVACIONES { get; set; }
        public string TAREAS { get; set; }
    
        public virtual ICollection<PRACTICA> PRACTICA { get; set; }
    }
}
