//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTA2
    {
        public ACTA2()
        {
            this.PRACTICA = new HashSet<PRACTICA>();
        }
    
        public short IDACTA2 { get; set; }
        public string PRINCIPALES_TAREAS { get; set; }
        public string APORTES { get; set; }
        public string SUGERENCIAS { get; set; }
        public short PROMEDIO_PERSONAL { get; set; }
        public short PROMEDIO_PROFESIONAL { get; set; }
    
        public virtual ICollection<PRACTICA> PRACTICA { get; set; }
    }
}
