//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRERA
    {
        public CARRERA()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int IDCARRERA { get; set; }
        public string NOMBRE_CARRERA { get; set; }
        public int ESCUELA_IDESCUELA { get; set; }
        public string ESCUELA_NOMBRE_ESCUELA { get; set; }
    
        public virtual ESCUELA ESCUELA { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
