//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESCUELA
    {
        public ESCUELA()
        {
            this.CARRERA = new HashSet<CARRERA>();
        }
    
        public int IDESCUELA { get; set; }
        public string NOMBRE_ESCUELA { get; set; }
        public string DIRECTOR_CARRERA { get; set; }
    
        public virtual ICollection<CARRERA> CARRERA { get; set; }
    }
}
