//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Core.Objects;
    using System.Data.Entity.Infrastructure;

    public partial class ProyectoEntities : DbContext
    {
        public ProyectoEntities()
            : base("name=ProyectoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACTA1> ACTA1 { get; set; }
        public DbSet<ACTA2> ACTA2 { get; set; }
        public DbSet<CARRERA> CARRERA { get; set; }
        public DbSet<CENTRO_PRACTICA> CENTRO_PRACTICA { get; set; }
        public DbSet<ESCUELA> ESCUELA { get; set; }
        public DbSet<PRACTICA> PRACTICA { get; set; }
        public DbSet<ROLES> ROLES { get; set; }
        public DbSet<SEDE> SEDE { get; set; }
        public DbSet<SISTEMA> SISTEMA { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int BUSCAR_USUARIO(Nullable<decimal> p_RUT, string p_DV_USUARIO, Nullable<decimal> p_ROL, ObjectParameter p_CONTRASENNA, ObjectParameter p_NOMBRES, ObjectParameter p_APELLIDO1, ObjectParameter p_APELLIDO2, ObjectParameter p_FECHA_NACIMIENTO, ObjectParameter p_DIRECCION, ObjectParameter p_TELEFONO, ObjectParameter p_EMAIL, ObjectParameter p_SEDE_ID, ObjectParameter p_SEDE_NOMBRE, ObjectParameter p_PRACTICA_ID, ObjectParameter p_CARRERA_ID, ObjectParameter p_CARRERA_NOMBRE)
        {
            var p_RUTParameter = p_RUT.HasValue ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(decimal));
    
            var p_DV_USUARIOParameter = p_DV_USUARIO != null ?
                new ObjectParameter("P_DV_USUARIO", p_DV_USUARIO) :
                new ObjectParameter("P_DV_USUARIO", typeof(string));
    
            var p_ROLParameter = p_ROL.HasValue ?
                new ObjectParameter("P_ROL", p_ROL) :
                new ObjectParameter("P_ROL", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BUSCAR_USUARIO", p_RUTParameter, p_DV_USUARIOParameter, p_ROLParameter, p_CONTRASENNA, p_NOMBRES, p_APELLIDO1, p_APELLIDO2, p_FECHA_NACIMIENTO, p_DIRECCION, p_TELEFONO, p_EMAIL, p_SEDE_ID, p_SEDE_NOMBRE, p_PRACTICA_ID, p_CARRERA_ID, p_CARRERA_NOMBRE);
        }
    
        public virtual int CREAR_ACTA2(string p_TAREAS, string p_APORTES, string p_SEGURENCIAS, Nullable<decimal> p_PROM_PERSONAL, Nullable<decimal> p_PROM_PROFE, string p_NOM_CENTRO, string p_DIRECC_CENTRO, string p_RAZON_SOCIAL, string p_WEB, Nullable<decimal> p_FONO, string p_EMAIL, Nullable<decimal> p_ID_CENTRO, Nullable<decimal> p_ID_PRACTICA)
        {
            var p_TAREASParameter = p_TAREAS != null ?
                new ObjectParameter("P_TAREAS", p_TAREAS) :
                new ObjectParameter("P_TAREAS", typeof(string));
    
            var p_APORTESParameter = p_APORTES != null ?
                new ObjectParameter("P_APORTES", p_APORTES) :
                new ObjectParameter("P_APORTES", typeof(string));
    
            var p_SEGURENCIASParameter = p_SEGURENCIAS != null ?
                new ObjectParameter("P_SEGURENCIAS", p_SEGURENCIAS) :
                new ObjectParameter("P_SEGURENCIAS", typeof(string));
    
            var p_PROM_PERSONALParameter = p_PROM_PERSONAL.HasValue ?
                new ObjectParameter("P_PROM_PERSONAL", p_PROM_PERSONAL) :
                new ObjectParameter("P_PROM_PERSONAL", typeof(decimal));
    
            var p_PROM_PROFEParameter = p_PROM_PROFE.HasValue ?
                new ObjectParameter("P_PROM_PROFE", p_PROM_PROFE) :
                new ObjectParameter("P_PROM_PROFE", typeof(decimal));
    
            var p_NOM_CENTROParameter = p_NOM_CENTRO != null ?
                new ObjectParameter("P_NOM_CENTRO", p_NOM_CENTRO) :
                new ObjectParameter("P_NOM_CENTRO", typeof(string));
    
            var p_DIRECC_CENTROParameter = p_DIRECC_CENTRO != null ?
                new ObjectParameter("P_DIRECC_CENTRO", p_DIRECC_CENTRO) :
                new ObjectParameter("P_DIRECC_CENTRO", typeof(string));
    
            var p_RAZON_SOCIALParameter = p_RAZON_SOCIAL != null ?
                new ObjectParameter("P_RAZON_SOCIAL", p_RAZON_SOCIAL) :
                new ObjectParameter("P_RAZON_SOCIAL", typeof(string));
    
            var p_WEBParameter = p_WEB != null ?
                new ObjectParameter("P_WEB", p_WEB) :
                new ObjectParameter("P_WEB", typeof(string));
    
            var p_FONOParameter = p_FONO.HasValue ?
                new ObjectParameter("P_FONO", p_FONO) :
                new ObjectParameter("P_FONO", typeof(decimal));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_ID_CENTROParameter = p_ID_CENTRO.HasValue ?
                new ObjectParameter("P_ID_CENTRO", p_ID_CENTRO) :
                new ObjectParameter("P_ID_CENTRO", typeof(decimal));
    
            var p_ID_PRACTICAParameter = p_ID_PRACTICA.HasValue ?
                new ObjectParameter("P_ID_PRACTICA", p_ID_PRACTICA) :
                new ObjectParameter("P_ID_PRACTICA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREAR_ACTA2", p_TAREASParameter, p_APORTESParameter, p_SEGURENCIASParameter, p_PROM_PERSONALParameter, p_PROM_PROFEParameter, p_NOM_CENTROParameter, p_DIRECC_CENTROParameter, p_RAZON_SOCIALParameter, p_WEBParameter, p_FONOParameter, p_EMAILParameter, p_ID_CENTROParameter, p_ID_PRACTICAParameter);
        }
    
        public virtual int CREAR_CARRERA(string nOMBRE_CARRERA, Nullable<decimal> iD_ESCUELA, string nOMBRE_ESCUELA)
        {
            var nOMBRE_CARRERAParameter = nOMBRE_CARRERA != null ?
                new ObjectParameter("NOMBRE_CARRERA", nOMBRE_CARRERA) :
                new ObjectParameter("NOMBRE_CARRERA", typeof(string));
    
            var iD_ESCUELAParameter = iD_ESCUELA.HasValue ?
                new ObjectParameter("ID_ESCUELA", iD_ESCUELA) :
                new ObjectParameter("ID_ESCUELA", typeof(decimal));
    
            var nOMBRE_ESCUELAParameter = nOMBRE_ESCUELA != null ?
                new ObjectParameter("NOMBRE_ESCUELA", nOMBRE_ESCUELA) :
                new ObjectParameter("NOMBRE_ESCUELA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREAR_CARRERA", nOMBRE_CARRERAParameter, iD_ESCUELAParameter, nOMBRE_ESCUELAParameter);
        }
    
        public virtual int CREAR_SEDE(string nOMBRE_SEDE, string dIRECCION_SEDE)
        {
            var nOMBRE_SEDEParameter = nOMBRE_SEDE != null ?
                new ObjectParameter("NOMBRE_SEDE", nOMBRE_SEDE) :
                new ObjectParameter("NOMBRE_SEDE", typeof(string));
    
            var dIRECCION_SEDEParameter = dIRECCION_SEDE != null ?
                new ObjectParameter("DIRECCION_SEDE", dIRECCION_SEDE) :
                new ObjectParameter("DIRECCION_SEDE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREAR_SEDE", nOMBRE_SEDEParameter, dIRECCION_SEDEParameter);
        }
    
        public virtual int CREAR_USUARIO(Nullable<decimal> rUT, string dV_USUARIO, string cONTRASENNA, string nOMBRES, string aPELLIDO1, string aPELLIDO2, string fECHA_NACIMIENTO, string dIRECCION, Nullable<decimal> tELEFONO, string cORREO, Nullable<decimal> iD_SEDE, string nOMBRE_SEDE, Nullable<decimal> iD_ROL, Nullable<decimal> iD_PRACTICA, Nullable<decimal> iD_CARRERA, string nOMBRE_CARRERA)
        {
            var rUTParameter = rUT.HasValue ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(decimal));
    
            var dV_USUARIOParameter = dV_USUARIO != null ?
                new ObjectParameter("DV_USUARIO", dV_USUARIO) :
                new ObjectParameter("DV_USUARIO", typeof(string));
    
            var cONTRASENNAParameter = cONTRASENNA != null ?
                new ObjectParameter("CONTRASENNA", cONTRASENNA) :
                new ObjectParameter("CONTRASENNA", typeof(string));
    
            var nOMBRESParameter = nOMBRES != null ?
                new ObjectParameter("NOMBRES", nOMBRES) :
                new ObjectParameter("NOMBRES", typeof(string));
    
            var aPELLIDO1Parameter = aPELLIDO1 != null ?
                new ObjectParameter("APELLIDO1", aPELLIDO1) :
                new ObjectParameter("APELLIDO1", typeof(string));
    
            var aPELLIDO2Parameter = aPELLIDO2 != null ?
                new ObjectParameter("APELLIDO2", aPELLIDO2) :
                new ObjectParameter("APELLIDO2", typeof(string));
    
            var fECHA_NACIMIENTOParameter = fECHA_NACIMIENTO != null ?
                new ObjectParameter("FECHA_NACIMIENTO", fECHA_NACIMIENTO) :
                new ObjectParameter("FECHA_NACIMIENTO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(decimal));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(decimal));
    
            var nOMBRE_SEDEParameter = nOMBRE_SEDE != null ?
                new ObjectParameter("NOMBRE_SEDE", nOMBRE_SEDE) :
                new ObjectParameter("NOMBRE_SEDE", typeof(string));
    
            var iD_ROLParameter = iD_ROL.HasValue ?
                new ObjectParameter("ID_ROL", iD_ROL) :
                new ObjectParameter("ID_ROL", typeof(decimal));
    
            var iD_PRACTICAParameter = iD_PRACTICA.HasValue ?
                new ObjectParameter("ID_PRACTICA", iD_PRACTICA) :
                new ObjectParameter("ID_PRACTICA", typeof(decimal));
    
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(decimal));
    
            var nOMBRE_CARRERAParameter = nOMBRE_CARRERA != null ?
                new ObjectParameter("NOMBRE_CARRERA", nOMBRE_CARRERA) :
                new ObjectParameter("NOMBRE_CARRERA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREAR_USUARIO", rUTParameter, dV_USUARIOParameter, cONTRASENNAParameter, nOMBRESParameter, aPELLIDO1Parameter, aPELLIDO2Parameter, fECHA_NACIMIENTOParameter, dIRECCIONParameter, tELEFONOParameter, cORREOParameter, iD_SEDEParameter, nOMBRE_SEDEParameter, iD_ROLParameter, iD_PRACTICAParameter, iD_CARRERAParameter, nOMBRE_CARRERAParameter);
        }
    
        public virtual int EDITAR_CARRERA(Nullable<decimal> iD_CARRERA, string nOMBRE_CARRERA, Nullable<decimal> iD_ESCUELA, string nOMBRE_ESCUELA)
        {
            var iD_CARRERAParameter = iD_CARRERA.HasValue ?
                new ObjectParameter("ID_CARRERA", iD_CARRERA) :
                new ObjectParameter("ID_CARRERA", typeof(decimal));
    
            var nOMBRE_CARRERAParameter = nOMBRE_CARRERA != null ?
                new ObjectParameter("NOMBRE_CARRERA", nOMBRE_CARRERA) :
                new ObjectParameter("NOMBRE_CARRERA", typeof(string));
    
            var iD_ESCUELAParameter = iD_ESCUELA.HasValue ?
                new ObjectParameter("ID_ESCUELA", iD_ESCUELA) :
                new ObjectParameter("ID_ESCUELA", typeof(decimal));
    
            var nOMBRE_ESCUELAParameter = nOMBRE_ESCUELA != null ?
                new ObjectParameter("NOMBRE_ESCUELA", nOMBRE_ESCUELA) :
                new ObjectParameter("NOMBRE_ESCUELA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EDITAR_CARRERA", iD_CARRERAParameter, nOMBRE_CARRERAParameter, iD_ESCUELAParameter, nOMBRE_ESCUELAParameter);
        }
    
        public virtual int EDITAR_SEDE(Nullable<decimal> iD_SEDE, string nOMBRE_SEDE, string dIRECCION_SEDE)
        {
            var iD_SEDEParameter = iD_SEDE.HasValue ?
                new ObjectParameter("ID_SEDE", iD_SEDE) :
                new ObjectParameter("ID_SEDE", typeof(decimal));
    
            var nOMBRE_SEDEParameter = nOMBRE_SEDE != null ?
                new ObjectParameter("NOMBRE_SEDE", nOMBRE_SEDE) :
                new ObjectParameter("NOMBRE_SEDE", typeof(string));
    
            var dIRECCION_SEDEParameter = dIRECCION_SEDE != null ?
                new ObjectParameter("DIRECCION_SEDE", dIRECCION_SEDE) :
                new ObjectParameter("DIRECCION_SEDE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EDITAR_SEDE", iD_SEDEParameter, nOMBRE_SEDEParameter, dIRECCION_SEDEParameter);
        }
    
        public virtual int EDITAR_USUARIO(Nullable<decimal> p_RUT, string p_DV_USUARIO, string p_CONTRASENNA, string p_NOMBRES, string p_APELLIDO1, string p_APELLIDO2, string p_FECHA_NACIMIENTO, string p_DIRECCION, Nullable<decimal> p_TELEFONO, string p_CORREO, Nullable<decimal> p_ID_SEDE, string p_NOMBRE_SEDE, Nullable<decimal> p_ID_ROL, Nullable<decimal> p_ID_PRACTICA, Nullable<decimal> p_ID_CARRERA, string p_NOMBRE_CARRERA)
        {
            var p_RUTParameter = p_RUT.HasValue ?
                new ObjectParameter("P_RUT", p_RUT) :
                new ObjectParameter("P_RUT", typeof(decimal));
    
            var p_DV_USUARIOParameter = p_DV_USUARIO != null ?
                new ObjectParameter("P_DV_USUARIO", p_DV_USUARIO) :
                new ObjectParameter("P_DV_USUARIO", typeof(string));
    
            var p_CONTRASENNAParameter = p_CONTRASENNA != null ?
                new ObjectParameter("P_CONTRASENNA", p_CONTRASENNA) :
                new ObjectParameter("P_CONTRASENNA", typeof(string));
    
            var p_NOMBRESParameter = p_NOMBRES != null ?
                new ObjectParameter("P_NOMBRES", p_NOMBRES) :
                new ObjectParameter("P_NOMBRES", typeof(string));
    
            var p_APELLIDO1Parameter = p_APELLIDO1 != null ?
                new ObjectParameter("P_APELLIDO1", p_APELLIDO1) :
                new ObjectParameter("P_APELLIDO1", typeof(string));
    
            var p_APELLIDO2Parameter = p_APELLIDO2 != null ?
                new ObjectParameter("P_APELLIDO2", p_APELLIDO2) :
                new ObjectParameter("P_APELLIDO2", typeof(string));
    
            var p_FECHA_NACIMIENTOParameter = p_FECHA_NACIMIENTO != null ?
                new ObjectParameter("P_FECHA_NACIMIENTO", p_FECHA_NACIMIENTO) :
                new ObjectParameter("P_FECHA_NACIMIENTO", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(decimal));
    
            var p_CORREOParameter = p_CORREO != null ?
                new ObjectParameter("P_CORREO", p_CORREO) :
                new ObjectParameter("P_CORREO", typeof(string));
    
            var p_ID_SEDEParameter = p_ID_SEDE.HasValue ?
                new ObjectParameter("P_ID_SEDE", p_ID_SEDE) :
                new ObjectParameter("P_ID_SEDE", typeof(decimal));
    
            var p_NOMBRE_SEDEParameter = p_NOMBRE_SEDE != null ?
                new ObjectParameter("P_NOMBRE_SEDE", p_NOMBRE_SEDE) :
                new ObjectParameter("P_NOMBRE_SEDE", typeof(string));
    
            var p_ID_ROLParameter = p_ID_ROL.HasValue ?
                new ObjectParameter("P_ID_ROL", p_ID_ROL) :
                new ObjectParameter("P_ID_ROL", typeof(decimal));
    
            var p_ID_PRACTICAParameter = p_ID_PRACTICA.HasValue ?
                new ObjectParameter("P_ID_PRACTICA", p_ID_PRACTICA) :
                new ObjectParameter("P_ID_PRACTICA", typeof(decimal));
    
            var p_ID_CARRERAParameter = p_ID_CARRERA.HasValue ?
                new ObjectParameter("P_ID_CARRERA", p_ID_CARRERA) :
                new ObjectParameter("P_ID_CARRERA", typeof(decimal));
    
            var p_NOMBRE_CARRERAParameter = p_NOMBRE_CARRERA != null ?
                new ObjectParameter("P_NOMBRE_CARRERA", p_NOMBRE_CARRERA) :
                new ObjectParameter("P_NOMBRE_CARRERA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("EDITAR_USUARIO", p_RUTParameter, p_DV_USUARIOParameter, p_CONTRASENNAParameter, p_NOMBRESParameter, p_APELLIDO1Parameter, p_APELLIDO2Parameter, p_FECHA_NACIMIENTOParameter, p_DIRECCIONParameter, p_TELEFONOParameter, p_CORREOParameter, p_ID_SEDEParameter, p_NOMBRE_SEDEParameter, p_ID_ROLParameter, p_ID_PRACTICAParameter, p_ID_CARRERAParameter, p_NOMBRE_CARRERAParameter);
        }
    
        public virtual int ELIMINAR_CARRERA(string nOMBRE_CARRERA)
        {
            var nOMBRE_CARRERAParameter = nOMBRE_CARRERA != null ?
                new ObjectParameter("NOMBRE_CARRERA", nOMBRE_CARRERA) :
                new ObjectParameter("NOMBRE_CARRERA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_CARRERA", nOMBRE_CARRERAParameter);
        }
    
        public virtual int ELIMINAR_SEDE(string nOMBRE_SEDE)
        {
            var nOMBRE_SEDEParameter = nOMBRE_SEDE != null ?
                new ObjectParameter("NOMBRE_SEDE", nOMBRE_SEDE) :
                new ObjectParameter("NOMBRE_SEDE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINAR_SEDE", nOMBRE_SEDEParameter);
        }
    
        public virtual int INGRESAR_PRACTICA(Nullable<decimal> rUT_ALUMNO, Nullable<decimal> rUT_DOCENTE, string fECHA_INICIO, string fECHA_TERMINO, string tIPO_PRACTICA, Nullable<decimal> cANT_HORAS, Nullable<decimal> iDCENTRO, string nOMBRE_CENTRO)
        {
            var rUT_ALUMNOParameter = rUT_ALUMNO.HasValue ?
                new ObjectParameter("RUT_ALUMNO", rUT_ALUMNO) :
                new ObjectParameter("RUT_ALUMNO", typeof(decimal));
    
            var rUT_DOCENTEParameter = rUT_DOCENTE.HasValue ?
                new ObjectParameter("RUT_DOCENTE", rUT_DOCENTE) :
                new ObjectParameter("RUT_DOCENTE", typeof(decimal));
    
            var fECHA_INICIOParameter = fECHA_INICIO != null ?
                new ObjectParameter("FECHA_INICIO", fECHA_INICIO) :
                new ObjectParameter("FECHA_INICIO", typeof(string));
    
            var fECHA_TERMINOParameter = fECHA_TERMINO != null ?
                new ObjectParameter("FECHA_TERMINO", fECHA_TERMINO) :
                new ObjectParameter("FECHA_TERMINO", typeof(string));
    
            var tIPO_PRACTICAParameter = tIPO_PRACTICA != null ?
                new ObjectParameter("TIPO_PRACTICA", tIPO_PRACTICA) :
                new ObjectParameter("TIPO_PRACTICA", typeof(string));
    
            var cANT_HORASParameter = cANT_HORAS.HasValue ?
                new ObjectParameter("CANT_HORAS", cANT_HORAS) :
                new ObjectParameter("CANT_HORAS", typeof(decimal));
    
            var iDCENTROParameter = iDCENTRO.HasValue ?
                new ObjectParameter("IDCENTRO", iDCENTRO) :
                new ObjectParameter("IDCENTRO", typeof(decimal));
    
            var nOMBRE_CENTROParameter = nOMBRE_CENTRO != null ?
                new ObjectParameter("NOMBRE_CENTRO", nOMBRE_CENTRO) :
                new ObjectParameter("NOMBRE_CENTRO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESAR_PRACTICA", rUT_ALUMNOParameter, rUT_DOCENTEParameter, fECHA_INICIOParameter, fECHA_TERMINOParameter, tIPO_PRACTICAParameter, cANT_HORASParameter, iDCENTROParameter, nOMBRE_CENTROParameter);
        }
    
        public virtual int REPORTE_ESPEC_JEFE_CARRERA(Nullable<decimal> p_SEDE, Nullable<decimal> p_CARRERA, ObjectParameter p_RUT, ObjectParameter p_DV, ObjectParameter p_NOMBRES, ObjectParameter p_APELLIDO1, ObjectParameter p_APELLIDO2)
        {
            var p_SEDEParameter = p_SEDE.HasValue ?
                new ObjectParameter("P_SEDE", p_SEDE) :
                new ObjectParameter("P_SEDE", typeof(decimal));
    
            var p_CARRERAParameter = p_CARRERA.HasValue ?
                new ObjectParameter("P_CARRERA", p_CARRERA) :
                new ObjectParameter("P_CARRERA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REPORTE_ESPEC_JEFE_CARRERA", p_SEDEParameter, p_CARRERAParameter, p_RUT, p_DV, p_NOMBRES, p_APELLIDO1, p_APELLIDO2);
        }
    
        public virtual int REPORTE_GENERAL_JEFE_CARRERA(Nullable<decimal> p_SEDE, Nullable<decimal> p_CARRERA, ObjectParameter p_CANTIDAD_CURSO, ObjectParameter p_CANTIDAD_PENDIENTE, ObjectParameter p_CANTIDAD_FINALIZADA)
        {
            var p_SEDEParameter = p_SEDE.HasValue ?
                new ObjectParameter("P_SEDE", p_SEDE) :
                new ObjectParameter("P_SEDE", typeof(decimal));
    
            var p_CARRERAParameter = p_CARRERA.HasValue ?
                new ObjectParameter("P_CARRERA", p_CARRERA) :
                new ObjectParameter("P_CARRERA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REPORTE_GENERAL_JEFE_CARRERA", p_SEDEParameter, p_CARRERAParameter, p_CANTIDAD_CURSO, p_CANTIDAD_PENDIENTE, p_CANTIDAD_FINALIZADA);
        }
    
        public virtual int UPDATE_CENTRO(Nullable<decimal> iD_CENTRO, string p_NOM, string p_DIRECCION, string p_DEPTO, string p_AREA)
        {
            var iD_CENTROParameter = iD_CENTRO.HasValue ?
                new ObjectParameter("ID_CENTRO", iD_CENTRO) :
                new ObjectParameter("ID_CENTRO", typeof(decimal));
    
            var p_NOMParameter = p_NOM != null ?
                new ObjectParameter("P_NOM", p_NOM) :
                new ObjectParameter("P_NOM", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_DEPTOParameter = p_DEPTO != null ?
                new ObjectParameter("P_DEPTO", p_DEPTO) :
                new ObjectParameter("P_DEPTO", typeof(string));
    
            var p_AREAParameter = p_AREA != null ?
                new ObjectParameter("P_AREA", p_AREA) :
                new ObjectParameter("P_AREA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_CENTRO", iD_CENTROParameter, p_NOMParameter, p_DIRECCIONParameter, p_DEPTOParameter, p_AREAParameter);
        }
    }
}
