//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACTICA
    {
        public PRACTICA()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public short IDPRACTICA { get; set; }
        public string TIPO_HORAS_PRACTICA { get; set; }
        public short CANT_HORAS { get; set; }
        public System.DateTime FECHA_TERMINO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public string DISTANCIA { get; set; }
        public string DONDE { get; set; }
        public decimal NOTA_FINAL { get; set; }
        public short ACTA1_IDACTA1 { get; set; }
        public Nullable<short> ACTA2_IDACTA2 { get; set; }
        public int IDCENTROPRACTICA { get; set; }
        public Nullable<short> ESTADO { get; set; }
    
        public virtual ACTA1 ACTA1 { get; set; }
        public virtual ACTA2 ACTA2 { get; set; }
        public virtual CENTRO_PRACTICA CENTRO_PRACTICA { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
