//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEDE
    {
        public SEDE()
        {
            this.USUARIO = new HashSet<USUARIO>();
        }
    
        public int IDSEDE { get; set; }
        public string NOMBRE_SEDE { get; set; }
        public string DIRECCION_SEDE { get; set; }
    
        public virtual ICollection<USUARIO> USUARIO { get; set; }
    }
}
