//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SISTEMA
    {
        public int IDNOTIFICACION { get; set; }
        public string NOMBRE_NOTIFICACION { get; set; }
        public System.DateTime FECHA_HORA { get; set; }
        public int USUARIO_RUT { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
