//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portafolio.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.SISTEMA = new HashSet<SISTEMA>();
        }
    
        public int RUT { get; set; }
        public string DV_USUARIO { get; set; }
        public string CONTRASEÑA { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDO1 { get; set; }
        public string APELLIDO2 { get; set; }
        public System.DateTime FECHA_NACIMIENTO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> TELEFONO { get; set; }
        public string CORREO { get; set; }
        public int SEDE_IDSEDE { get; set; }
        public string SEDE_NOMBRE_SEDE { get; set; }
        public short ROLES_IDROL { get; set; }
        public Nullable<short> PRACTICA_IDPRACTICA { get; set; }
        public int CARRERA_IDCARRERA { get; set; }
        public string CARRERA_NOMBRE_CARRERA { get; set; }
    
        public virtual CARRERA CARRERA { get; set; }
        public virtual PRACTICA PRACTICA { get; set; }
        public virtual ROLES ROLES { get; set; }
        public virtual SEDE SEDE { get; set; }
        public virtual ICollection<SISTEMA> SISTEMA { get; set; }
    }
}
